name: python

on: push


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
           python-version: 'pypy3.10' 
      - run: which python
      - run: python -c "import sys; print(sys.version)"
